
# COMMENTS ----------------------------------------------------------------
#
# Generated by David Leclere (leclere@iiasa.ac.at) on 20 Dec 2017
# Based on previous inputs from Piero Visonti (pierovisconti@gmail.com)
# Timing: cfor now about 2 min per file

# LOAD DATA ---------------------------------------------------------------

indexFun <- function(version){
inputdir <- paste('RLIscore_forAIM\\input_scenarios\\', version, '\\', sep = '') 
outputfile <- paste('RLIscore_forAIM\\output\\BiodivIndicator_trends_AIM_', version, '.csv', sep='')

# -- scenario files
#files_by_scenario <- list.files('input_scenarios')
files_by_scenario <- list.files(inputdir)

# -- link LUIDs to AGMIP regions
#load('other_inputs/Link_to_regions.Rdata')
load('RLIscore_forAIM/other_inputs/Link_to_regions.Rdata')
# to adjust the LUID
#link_AgMIP_Reg_ID_LUID <-  link_AgMIP_Reg_ID_LUID %>%
#  killfactor() %>%
#  mutate(LUID =as.factor(paste("LU", formatC(as.numeric(substr(LUID,3,7))-1, digits = 5, flag = 0), sep = "")))


# link_AgMIP_Reg_ID_LUID

# -- species data
#load('other_inputs/speciesdata.rdata')
load('RLIscore_forAIM/other_inputs/speciesdata.rdata')
# add another value for restoration land (assuming all 1s)
specieslanduse <- cbind(specieslanduse,rep(1,dim(specieslanduse)[1])) # add another category at the end for restoration
# save common_set
common_set_save <- common_set


# DEFINE FUNCTIONS --------------------------------------------------------

interpolate=function(tointerpolate,inputyears,allyears){
  interpolated <- NULL
  for(i in 1:nrow(tointerpolate)) {
    if(is.na(tointerpolate[i,2]) ){
      data.new_line=c(tointerpolate[i,1],rep(NA,length(allyears)))
    } else {
      data.spline.f <- splinefun(inputyears,tointerpolate[i,],method='monoH.FC')
      data.new_line <- data.spline.f(allyears)
    }
    interpolated <- rbind(interpolated,data.new_line)}
  return(interpolated)
} # function to do interpolation

gm_mean = function(x, na.rm=TRUE){
  lines_x <- which(x > 0 & !is.infinite(x))
  if (length(lines_x)==0) {
    return(NA)
  } else {
    return(exp(sum(log(x[lines_x]), na.rm=na.rm) / length(x[lines_x])))
  }
} # geometric mean


# PROCESS -----------------------------------------------------------------

# -- loop on scenarios
file_df <- cbind.data.frame('file'=files_by_scenario,'id_file'=c(1:length(files_by_scenario)))
#test <- read.csv(paste('input_scenarios',file_df$file[1],sep='/'))
test <- read.csv(paste(inputdir,file_df$file[1],sep='/'))
years <- unique(test$YEAR)
vars_output <- c('ESHI','RLI','NSpeciesExtinctAtFirstYear','NPotSpeciesInRegion')
outputs <- years
regions <- c("CAN","USA","BRA","OSA","FSU","EUR","MEN","SSA","CHN","IND",
             "SEA","OAS","ANZ","NAM","OAM","AME","SAS","WLD","EUE")
reg_template_output <- cbind.data.frame(expand.grid('id_file'=file_df$id_file,'reg'=regions,'variable'=vars_output,'year'=years), 'val'=NA)
reg_template_output <- merge(reg_template_output,file_df,by='id_file')

## add this line to sort by YEAR
reg_template_output <- reg_template_output[ order(reg_template_output$year),]

# here we go
for(curfile in file_df$id_file) {
  
  cat('\n');
  cat(paste(format(Sys.time()),'-- Processing file',curfile,'out of',dim(file_df)[1]))
  cat('\n'); cat('  ')
  
  #cur_input <- read.csv(paste('input_scenarios/',file_df$file[which(file_df$id_file==curfile)],sep='/'),sep=',')
  cur_input <- read.csv(paste(inputdir,file_df$file[which(file_df$id_file==curfile)],sep='/'),sep=',')
  
  for(reg in regions) {
  
    cat(paste('.',reg,' ',sep = ''))

    #print(paste('before B]',Sys.time()))
    
    # get values for current region  
    cur_LUIDs_weights <- link_AgMIP_Reg_ID_LUID[which(link_AgMIP_Reg_ID_LUID[,which(colnames(link_AgMIP_Reg_ID_LUID)==reg)] > 0),c(1,2,which(colnames(link_AgMIP_Reg_ID_LUID)==reg))]
    colnames(cur_LUIDs_weights)[3] <- 'ID_LUID_weight'
    r_input <- cur_input[which(cur_input$ID_LUID%in%c(cur_LUIDs_weights$ID_LUID)),]
    
    # merge with weights and correct total area by LUID
    LU <- merge(r_input,cur_LUIDs_weights[,c('ID_LUID','ID_LUID_weight')], all.x = T) 
    LU$Area.1000ha <- LU$Area.1000ha * LU$ID_LUID_weight
    
    # isolate species of relevance
    sites_curreg <- link_AgMIP_Reg_ID_LUID$ID_LUID[which(link_AgMIP_Reg_ID_LUID[,which(colnames(link_AgMIP_Reg_ID_LUID)==reg)]==1)]
    sum_presence <- rowSums(speciesbysite[,sites_curreg])
    indices_species_present <- which(sum_presence > 0)
    
    # initialize totalsuit
    totalsuit=matrix(nrow=nspecies,ncol=length(years)) # initialize results
    allyears=years[1]:years[length(years)]
    outputyears=which(allyears %in% outputs)
    
    # B] ESTIMATE SUITABLE AREA BY SPECIES & TIME STEP ------------------------
    #print(paste('B]',Sys.time()))
    
    LU$YEAR <- as.numeric(as.character(LU$YEAR))
    
    for (i in 1:length(years)){
      year=years[i]
      LUyear=LU[LU$YEAR==year,c(1,5:15)] # extract landuse for the given year
      sitebylanduse=t(apply(LUyear,MARGIN=1,FUN=function(x) c(x[1],x[2:10]*x[11])))[,1:10] # multiply the fractional landuse for total area of the cell
      toadd=setdiff(1:4844,LUyear[,1]) # make sure that grid cells not in the table have a row
      toadd=cbind(toadd,matrix(rep(0,length(toadd)*9),ncol=9)) # create rows with all zeroes to add
      sitebylanduse=rbind(sitebylanduse,toadd)
      sitebylanduse=sitebylanduse[order(sitebylanduse[,1]),]
      sitebylanduse=sitebylanduse[,2:10]
      sitebylanduse[,8]=0 # zero not relevant LU
      suitbysite=specieslanduse %*% t(sitebylanduse) # matrix product of species habitat prefs for land-cover/land-use info
      speciesuite=suitbysite * speciesbysite # filter by climate change (speciesbysite is the suitable climate)
      totalsuit[,i]=c(speciesuite %*% matrix(1,nrow=nsites,ncol=1)) # give 1 value for species
    }
    
    # C] FILTER OUT SPECIES NOT EXPECTED THERE ----------------------
    #print(paste('C]',Sys.time()))
    
    # look at species that will considered already extinct (for the region) due to missing area
    lines_with_zero_area <- which(totalsuit[,1]==0)
    lines_with_zero_area_not_expected <- which(lines_with_zero_area%in%c(indices_species_present))
    
    number_missing <- length(lines_with_zero_area_not_expected)
    max_number_of_species <- length(indices_species_present)
    number_species_accounted <- max_number_of_species - number_missing
    
    # filter out only species not expected in the region 
    totalsuit <- totalsuit[indices_species_present,]
    common_set <- common_set_save[indices_species_present]

    
    # D] INTERPOLATE IN TIME --------------------------------------------------
    #print(paste('D]',Sys.time()))
    
    inputyears=years; 
    BASE_AOO_interp=cbind(common_set,interpolate(totalsuit,inputyears,allyears)) # interpolate suitable areas
    
    # E] ESTIMATE RLI ---------------------------------------------------------
    #print(paste('E]',Sys.time()))
    
    # run code to calculate extinction risk category if the species reached the target area
    
    #source(paste('other_inputs','RL2050.A2aoo.new.R',sep='/'));
    #A2=A2_AOO_interp_rl # extinction risk based on rate of decline population (extent of suitable habitat taken as proxy) standardized by generation length
    source(paste('RLIscore_forAIM/other_inputs','RL2050.A2aoo.newFun.R',sep='/'))
    A2 = A2Fun(BASE_AOO_interp, genlentable)
    #print(paste('E] after A2',Sys.time()))
    
    #source(paste('other_inputs','RL2050.B2.R',sep='/'));
    #B2=B2_AOO_interp_rl # extinction risk based on extent of AOO
    source(paste('RLIscore_forAIM/other_inputs','RL2050.B2Fun.R',sep='/'))
    B2 = B2Fun(BASE_AOO_interp) # extinction risk based on extent of AOO
    #print(paste('E] after B2',Sys.time()))
    RL=pmax(A2,B2,na.rm=TRUE)
    RLI=apply(RL[,-1],MARGIN=2, FUN=function(x) 1-(sum(x)/(length(x)*5)))
    #print(paste('E] end',Sys.time()))
    
    # F] ESTIMATE ESHI --------------------------------------------------------
    #print(paste('F]',Sys.time()))
    
    # geometric mean of ratio of suitable habitat across 2843 species of mammals
    ESHI <- apply(BASE_AOO_interp[,-1],MARGIN=2,FUN=function(x) gm_mean(x/totalsuit[,1], na.rm=TRUE))
    
    # G] EXPORT ---------------------------------------------------------------
    
    # print('-- Biodiversity indicators for years')
    # print(paste(years, collapse = ','))
    # print('-- Extent of Suitable Habitat Index ESHI')
    # print(paste(round(ESHI[outputyears], digit=4), collapse = ','))
    # print('-- Red List Index RLI')
    # print(paste(round(RLI[outputyears],digit=4), collapse = ','))
    
    # H] store ----------------------------------------------------------------
    reg_template_output$val[which(reg_template_output$id_file==curfile 
                                  & reg_template_output$reg==reg 
                                  & reg_template_output$variable=='ESHI')] <- ESHI[outputyears]
    reg_template_output$val[which(reg_template_output$id_file==curfile  
                                  & reg_template_output$reg==reg 
                                  & reg_template_output$variable=='RLI')] <- RLI[outputyears]
    reg_template_output$val[which(reg_template_output$id_file==curfile 
                                  & reg_template_output$reg==reg 
                                  & reg_template_output$variable=='NSpeciesExtinctAtFirstYear')] <- number_missing
    reg_template_output$val[which(reg_template_output$id_file==curfile 
                                  & reg_template_output$reg==reg 
                                  & reg_template_output$variable=='NPotSpeciesInRegion')] <- max_number_of_species

  }
  
}


# EXPORT ------------------------------------------------------------------

output <- reg_template_output[order(reg_template_output$id_file,reg_template_output$variable, reg_template_output$year),]
write.table(output, outputfile, col.names = T, row.names = F, quote = F, sep=',')

}


